from setuptools import setup, find_packages
setup(
    name='nlm-ingestor',
    version='0.1.7',    
    description='Parsers and ingestors for different file types and formats',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/nlmatics/nlm-ingestor',
    author='Ambika Sukla',
    author_email='ambika.sukla@nlmatics.com',
    license='Apache License 2.0',
    packages=find_packages(),
    include_package_data=True,
    package_data={'': ['ingestor_utils/*.txt', ]},
    install_requires=[
        "flask==3.0.3",
        "flask_restful==0.3.10",
        "flask_jsonpify==1.5.0",
        "gunicorn==22.0.0",
        "werkzeug==3.0.2",
        "tika==2.6.0",
        "bs4==0.0.2",
        "nltk==3.6.2",
        "python-magic==0.4.22",
        "numpy==1.24.4",
        "tqdm==4.66.2",
        "symspellpy==6.7.0",
        "pandas==1.5.3",
        "mistune==2.0.3",
        "lxml==4.9.1",
        "unidecode==1.3.8",
        "nlm-utils==0.1.2",
        "boto3==1.34.79",
        "html5lib==1.1"
    ],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Development Status :: 1 - Planning',
        'Intended Audience :: Science/Research',
        'Intended Audience :: Developers',
        'Intended Audience :: Legal Industry',
        'License :: OSI Approved :: Apache Software License',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 3 :: Only'        
    ],
)